version: "3"

services: 
    app:
        build: 
            context: .
        ports:
            - "8000:8000" # maps host's 8000 to container's port 8000
        volumes:
            - ./app:/app # maps local app folder to container's app folder for live updates
        command: >
            sh -c "python manage.py wait_for_db &&
                    python manage.py migrate && 
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db

    db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword # build server encrypted env variable overrides this in prod
